name : Deploy Dev
on:
  workflow_dispatch:
permissions:
  id-token: write   # 👈 REQUIRED
  contents: read  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::427606711694:role/github-terraform-role
          aws-region: ap-south-1
      - name: Terraform Init
        run: |
          cd envs/dev
          terraform init

      - name: Terraform Plan
        run: |
          cd envs/dev
          terraform plan     

      - name: Terraform Apply
        run: |
          cd envs/dev
          terraform apply     
          
            
